### ISSUE TITLE
Script version

### ISSUE THREAD

**Issue by Qwerty-Space** [SilverEzhik/umpvw#2]
Is there no way to add this as a script?

**Comment by SilverEzhik** [comment]
What do you mean?

**Comment by Qwerty-Space** [comment]
Like a script that you add to the scripts directory

**Comment by SilverEzhik** [comment]
The deal with this is that the issue lies not with mpv itself, but with how Windows handles opening multiple selected files. 

Rather than essentially doing this (macOS Finder behavior):

    mpv file1 file2 file3

Windows' explorer.exe essentially does this:

    mpv file1
    mpv file2
    mpv file3

To prevent that, umpvw will launch 3 processes, with each coordinating to make sure that they all end up using the same mpv window. 

In theory it might be possible to coordinate multiple running mpv instances using a similar method, but it will end up starting a new mpv instance for each of file that you try to open, which would require more time and would show visible windows for each mpv window, so I did not take this approach.

**Comment by Qwerty-Space** [comment]
How about just the single instance part?

**Comment by SilverEzhik** [comment]
Again, possible, but I didn't do it for the reasons described above. Lua should probably have some way of working with named pipes, so you can write a script to do that following a similar logic flow to my program, though thinking about it, I am not actually sure if mpv allows starting the IPC server from within Lua.

May I ask for what purpose you're trying to get this working without the separate application? If it's for getting single-instance mpv on a *nix, you might want to try the original [umpv script](https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv).
